run-dist: # запуск исполняемого файла
	./build/install/app/bin/app

build:
	./gradlew build

test:
	./gradlew test

checkstyle:
	./gradlew checkstyleMain checkstyleTest

sonar:
	./gradlew sonarqube

.PHONY: build