name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Добавьте настройку рабочей директории
      - name: Prepare workspace
        run: |
          echo "GRADLE_DIR=app" >> $GITHUB_ENV
          cd $GRADLE_DIR
          chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          working-directory: ${{ env.GRADLE_DIR }}
          fetch-depth: 0

      - name: Execute Gradle build
        run: ./gradlew build
        working-directory: ${{ env.GRADLE_DIR }}

      - name: Generate coverage report
        run: make report

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
        working-directory: ${{ env.GRADLE_DIR }}
